In [1]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /home/etd/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/etd/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/etd/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [2]:
nltk.download('punkt')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package punkt to /home/etd/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /home/etd/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /home/etd/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

# 1.	Les bases de la NLP

## 1.1.	Segmentation (Tokenization)

In [3]:
from nltk.tokenize import sent_tokenize, word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'

sentences=sent_tokenize(data) #divise en phrase
print(sentences)
words=word_tokenize(data)#divise en word token
print(words)

['Hello, i am very happy to meet you.', 'I created this course for you.', 'Good by!']
['Hello', ',', 'i', 'am', 'very', 'happy', 'to', 'meet', 'you', '.', 'I', 'created', 'this', 'course', 'for', 'you', '.', 'Good', 'by', '!']


## 1.2.	Nettoyage(Cleaning) 


In [4]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
data="Hello, i am very happy to meet you. I created this course for you. Good by!"
word_tokens = [word.lower() for word in word_tokenize(data)]
data_clean = [word for word in word_tokens if (not word in set(stopwords.words('english')) and  word.isalpha())]
print(data_clean)
#un mot vide (ou stop word, en anglais) est un mot qui est tellement commun qu'il est inutile de l'indexer ou de l'utiliser dans une recherche. En français, des mots vides évidents pourraient être « le », « la », « de », « du », « ce »…

['hello', 'happy', 'meet', 'created', 'course', 'good']


## 1.3.	Racinisation(Stemming)

In [4]:
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
#stemmer=SnowballStemmer('french')
stemmer=PorterStemmer()
data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
word_tokens = [word.lower() for word in word_tokenize(data)]

for i in range(len(word_tokens)):
    words=[stemmer.stem(word) for word in word_tokens if (not word in set(stopwords.words('french')) and  word.isalpha())]
print(words)

['big', 'data', 'gross', 'donné', 'anglai', 'mégadonné', 'donné', 'massiv', 'désign', 'ressourc', 'inform', 'dont', 'caractéristiqu', 'term', 'volum', 'vélocité', 'variété', 'impos', 'utilis', 'technolog', 'méthode', 'analytiqu', 'particulièr', 'générer', 'valeur', 'dépassent', 'général', 'capacité', 'seul', 'uniqu', 'machin', 'nécessit', 'traitement', 'parallélisé']


In [5]:
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stemmer=SnowballStemmer('french')
#stemmer=PorterStemmer()
data="Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés"
word_tokens = [word.lower() for word in word_tokenize(data)]

for i in range(len(words)):
    words=[stemmer.stem(word) for word in word_tokens if (not word in set(stopwords.words('french')) and  word.isalpha())]
print(words)

['big', 'dat', 'gross', 'don', 'anglais', 'mégadon', 'don', 'massiv', 'désign', 'ressourc', 'inform', 'dont', 'caractérist', 'term', 'volum', 'véloc', 'variet', 'imposent', 'utilis', 'technolog', 'méthod', 'analyt', 'particuli', 'géner', 'valeur', 'dep', 'général', 'capac', 'seul', 'uniqu', 'machin', 'nécessitent', 'trait', 'parallélis']


## 1.4.	Lemmatisation

In [6]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

lemmmatizer=WordNetLemmatizer()
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words = word_tokenize(data)
words = [lemmmatizer.lemmatize(word.lower()) for word in words if(not word in set(stopwords.words('english')) and  word.isalpha())]
print(words)

['big', 'data', 'field', 'treat', 'way', 'analyze', 'systematically', 'extract', 'information', 'otherwise', 'deal', 'data', 'set', 'large', 'complex', 'dealt', 'traditional', 'application', 'software', 'data', 'many', 'case', 'row', 'offer', 'greater', 'statistical', 'power', 'data', 'higher', 'complexity', 'attribute', 'column', 'may', 'lead', 'higher', 'false', 'discovery', 'rate']


## 3.5.	POS-Tagging

In [7]:
import nltk
from nltk.tokenize import word_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
words=word_tokenize(data)
print(nltk.pos_tag(words))

[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or', 

In [8]:
import nltk
from nltk.tokenize import sent_tokenize
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "


sentences=sent_tokenize(data)

list=[]
for sentence in sentences:
    list.append(word_tokenize(sentence))
    
print(nltk.pos_tag_sents(list))

[[('Big', 'NNP'), ('data', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('field', 'NN'), ('that', 'WDT'), ('treats', 'VBZ'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'VB'), (',', ','), ('systematically', 'RB'), ('extract', 'JJ'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'NN'), ('with', 'IN'), ('data', 'NNS'), ('sets', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('too', 'RB'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'VB'), ('dealt', 'VBN'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'JJ'), ('application', 'NN'), ('software', 'NN'), ('.', '.')], [('Data', 'NNP'), ('with', 'IN'), ('many', 'JJ'), ('cases', 'NNS'), ('(', '('), ('rows', 'NNS'), (')', ')'), ('offer', 'VBP'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'IN'), ('data', 'NNS'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'RBR'), ('attributes', 'NNS'), ('or

In [10]:
import nltk
nltk.download('brown')
from nltk.corpus import brown #The Brown Corpus was the first million-word electronic corpus of English
from nltk.tag import UnigramTagger
from nltk.tokenize import word_tokenize

brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
unigram_tagger = nltk.UnigramTagger(train_sents)
print(unigram_tagger.evaluate(test_sents))

data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(unigram_tagger.tag(word_tokenize(data)))

[nltk_data] Downloading package brown to /home/etd/nltk_data...
[nltk_data]   Package brown is already up-to-date!


0.8121200039868434
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', None), ('ways', 'NNS'), ('to', 'TO'), ('analyze', None), (',', ','), ('systematically', None), ('extract', None), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'JJ'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', None), ('application', 'NN'), ('software', None), ('.', '.'), ('Data', None), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', None), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

In [14]:
brown_tagged_sents = brown.tagged_sents(categories='news')
size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
bigram_tagger = nltk.BigramTagger(train_sents)
print(bigram_tagger.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(bigram_tagger.tag(word_tokenize(data.lower()))) #bigram= on traite deux termes par deux

0.10206319146815508
[('big', None), ('data', None), ('is', None), ('a', None), ('field', None), ('that', None), ('treats', None), ('ways', None), ('to', None), ('analyze', None), (',', None), ('systematically', None), ('extract', None), ('information', None), ('from', None), (',', None), ('or', None), ('otherwise', None), ('deal', None), ('with', None), ('data', None), ('sets', None), ('that', None), ('are', None), ('too', None), ('large', None), ('or', None), ('complex', None), ('to', None), ('be', None), ('dealt', None), ('with', None), ('by', None), ('traditional', None), ('data-processing', None), ('application', None), ('software', None), ('.', None), ('data', None), ('with', None), ('many', None), ('cases', None), ('(', None), ('rows', None), (')', None), ('offer', None), ('greater', None), ('statistical', None), ('power', None), (',', None), ('while', None), ('data', None), ('with', None), ('higher', None), ('complexity', None), ('(', None), ('more', None), ('attributes', None),

In [24]:
brown_tagged_sents = brown.tagged_sents(categories='news')

size = int(len(brown_tagged_sents) * 0.9)
train_sents = brown_tagged_sents[:size]
test_sents = brown_tagged_sents[size:]
t0 = nltk.DefaultTagger('NN')
t1 = nltk.UnigramTagger(train_sents, backoff=t0)
t2 = nltk.BigramTagger(train_sents, backoff=t1)
print(t2.evaluate(test_sents))
data="Big data is a field that treats ways to analyze, systematically extract information from," \
     " or otherwise deal with data sets that are too large or complex to be dealt with by traditional" \
     " data-processing application software. Data with many cases (rows) offer greater statistical power," \
     " while data with higher complexity (more attributes or columns) " \
     "may lead to a higher false discovery rate. "
print(t2.tag(word_tokenize(data)))


0.8452108043456593
[('Big', 'JJ-TL'), ('data', 'NN'), ('is', 'BEZ'), ('a', 'AT'), ('field', 'NN'), ('that', 'CS'), ('treats', 'NN'), ('ways', 'NNS'), ('to', 'TO'), ('analyze', 'NN'), (',', ','), ('systematically', 'NN'), ('extract', 'NN'), ('information', 'NN'), ('from', 'IN'), (',', ','), ('or', 'CC'), ('otherwise', 'RB'), ('deal', 'VB'), ('with', 'IN'), ('data', 'NN'), ('sets', 'VBZ-HL'), ('that', 'CS'), ('are', 'BER'), ('too', 'QL'), ('large', 'JJ'), ('or', 'CC'), ('complex', 'NN'), ('to', 'TO'), ('be', 'BE'), ('dealt', 'VBD'), ('with', 'IN'), ('by', 'IN'), ('traditional', 'JJ'), ('data-processing', 'NN'), ('application', 'NN'), ('software', 'NN'), ('.', '.'), ('Data', 'NN'), ('with', 'IN'), ('many', 'AP'), ('cases', 'NNS'), ('(', '('), ('rows', 'NN'), (')', ')'), ('offer', 'VB'), ('greater', 'JJR'), ('statistical', 'JJ'), ('power', 'NN'), (',', ','), ('while', 'CS'), ('data', 'NN'), ('with', 'IN'), ('higher', 'JJR'), ('complexity', 'NN'), ('(', '('), ('more', 'AP'), ('attributes', 

## 3.6.	NER (Named Entity Recognition)

In [15]:
import nltk
from nltk.tokenize import word_tokenize
data="William Henry Gates III (born October 28, 1955) is an American business magnate," \
     " software developer, and philanthropist. He is best known as the co-founder of Microsoft Corporation." \
     "During his career at Microsoft, Gates held the positions of chairman, " \
     "chief executive officer (CEO), president and chief software architect, " \
     "while also being the largest individual shareholder until May 2014. " \
     "He is one of the best-known entrepreneurs and pioneers of the microcomputer " \
     "revolution of the 1970s and 1980s."
words=word_tokenize(data)
print(nltk.ne_chunk(nltk.pos_tag(words)))


(S
  (PERSON William/NNP)
  (PERSON Henry/NNP Gates/NNP III/NNP)
  (/(
  born/JJ
  October/NNP
  28/CD
  ,/,
  1955/CD
  )/)
  is/VBZ
  an/DT
  (GPE American/JJ)
  business/NN
  magnate/NN
  ,/,
  software/NN
  developer/NN
  ,/,
  and/CC
  philanthropist/NN
  ./.
  He/PRP
  is/VBZ
  best/RB
  known/VBN
  as/IN
  the/DT
  co-founder/NN
  of/IN
  (ORGANIZATION Microsoft/NNP)
  Corporation.During/VBG
  his/PRP$
  career/NN
  at/IN
  (ORGANIZATION Microsoft/NNP)
  ,/,
  (PERSON Gates/NNP)
  held/VBD
  the/DT
  positions/NNS
  of/IN
  chairman/NN
  ,/,
  chief/JJ
  executive/NN
  officer/NN
  (/(
  (ORGANIZATION CEO/NNP)
  )/)
  ,/,
  president/NN
  and/CC
  chief/NN
  software/NN
  architect/NN
  ,/,
  while/IN
  also/RB
  being/VBG
  the/DT
  largest/JJS
  individual/JJ
  shareholder/NN
  until/IN
  May/NNP
  2014/CD
  ./.
  He/PRP
  is/VBZ
  one/CD
  of/IN
  the/DT
  best-known/JJ
  entrepreneurs/NNS
  and/CC
  pioneers/NNS
  of/IN
  the/DT
  microcomputer/NN
  revolution/NN
  of/IN
  t

## 3.7.	WSD

In [16]:
from nltk.corpus import wordnet
for sens in wordnet.synsets('break'):
    print(">>>",sens.definition())


>>> some abrupt occurrence that interrupts an ongoing activity
>>> an unexpected piece of good luck
>>> (geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other
>>> a personal or social separation (as between opposing factions)
>>> a pause from doing something (as work)
>>> the act of breaking something
>>> a time interval during which there is a temporary cessation of something
>>> breaking of hard tissue such as bone
>>> the occurrence of breaking
>>> an abrupt change in the tone or register of the voice (as at puberty or due to emotion)
>>> the opening shot that scatters the balls in billiards or pool
>>> (tennis) a score consisting of winning a game when your opponent was serving
>>> an act of delaying or interrupting the continuity
>>> a sudden dash
>>> any frame in which a bowler fails to make a strike or spare
>>> an escape from jail
>>> terminate
>>> become separated into pieces or fragments
>>> render inoperable or ineffectiv

In [17]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
context= word_tokenize("I've just finished the first step of the competition. I need a little break to catch my breath")
print(lesk(context, 'break','n').definition())

(geology) a crack in the earth's crust resulting from the displacement of one side with respect to the other


In [19]:
# pip install pywsd
# pip install -U pywsd
#pip install wn==0.0.22
from pywsd.lesk import simple_lesk
sent = "I've just finished the first step of the competition. I need a little break to catch my breath"
ambiguous = 'break'
answer = simple_lesk(sent, ambiguous, pos='n')
print (answer)
print (answer.definition())
#It is based on the hypothesis that words used together 
#in text are related to each other and that the relation 
#can be observed in the definitions of the words and their senses.


Synset('rupture.n.02')
a personal or social separation (as between opposing factions)


## 3.8.	Spacy

In [21]:
#!pip install spacy
import spacy
nlp = spacy.load('fr_core_news_sm')
doc = nlp("Le big data  « grosses données » en anglais,les mégadonnées ou les données massives, " \
     "désigne les ressources d’informations dont les caractéristiques en termes de volume," \
     " de vélocité et de variété imposent l’utilisation de technologies et de méthodes analytiques " \
     "particulières pour générer de la valeur, et qui dépassent en général les capacités " \
     "d'une seule et unique machine et nécessitent des traitements parallélisés")

for token in doc:
    print("/token:",token.text, "/lemma:",token.lemma_, token.shape_, token.is_alpha, token.is_stop,"/POS:", token.tag_, "/PARS:", token.head, token.dep_, "/NER:", token.ent_iob_, token.ent_type_)

/token: Le /lemma: le Xx True True /POS: DET /PARS: big det /NER: O 
/token: big /lemma: big xxx True False /POS: NUM /PARS: data nummod /NER: O 
/token: data /lemma: data xxxx True False /POS: ADP /PARS: data ROOT /NER: O 
/token:   /lemma:     False False /POS: SPACE /PARS: data punct /NER: O 
/token: « /lemma: « « False False /POS: NOUN /PARS: « ROOT /NER: O 
/token: grosses /lemma: gros xxxx True False /POS: ADJ /PARS: données amod /NER: O 
/token: données /lemma: donnée xxxx True False /POS: NOUN /PARS: données ROOT /NER: O 
/token: » /lemma: » » False False /POS: PUNCT /PARS: données punct /NER: O 
/token: en /lemma: en xx True True /POS: ADP /PARS: anglais case /NER: O 
/token: anglais /lemma: anglais xxxx True False /POS: NOUN /PARS: données obl:mod /NER: O 
/token: , /lemma: , , False False /POS: PUNCT /PARS: désigne punct /NER: O 
/token: les /lemma: le xxx True True /POS: DET /PARS: mégadonnées det /NER: O 
/token: mégadonnées /lemma: mégadonnée xxxx True False /POS: NOUN /P

# 4.	Model représentatif d’un document

## 4.2. One-hot-vector

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.preprocessing import Binarizer

freq   = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
corpus = freq.fit_transform(corpus)
#print(corpus.toarray())
onehot = Binarizer()
corpus = onehot.fit_transform(corpus.toarray())
print(corpus)

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


## 4.1.	Bag-of-words

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
X = vectorizer.fit_transform(corpus) #sparsy format
print(X.toarray()) # explicit matrix format
print(vectorizer.get_feature_names() ) #vocabulary as list of string
vectorizer.vocabulary_.get('document') #get column index of a specific term in the vocabulary
vectorizer.transform(['Something completely new.']).toarray()#apply the model to a new document

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

## 4.2.	TF-IDF

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ['This is the first document.','this is the second second Document.','And the third one.','Is this the first document?']
vectorizer = TfidfVectorizer()
X=vectorizer.fit_transform(corpus)
print(X.toarray())
print(vectorizer.get_feature_names() )

#NB: le vecteur tf-idf obtenu sera normalisé pour obtenir des valeurs entre 0 et 1.

[[0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]
 [0.         0.27230147 0.         0.27230147 0.         0.85322574
  0.22262429 0.         0.27230147]
 [0.55280532 0.         0.         0.         0.55280532 0.
  0.28847675 0.55280532 0.        ]
 [0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


# 5.	Cas utilisations : Détection du Plagiarisme 

L’objectif de cet atelier est de détecter le pélagianisme à partir de wikipedia pendant la préparation des réponses à un certain nombre de questions sur des connaissances en informatique. Le dataset utilisé peut-être récupéré à partir du lien suivant :Cliquer <a href="https://ir.shef.ac.uk/cloughie/resources/plagiarism_corpus.html#Download" target="_blank">ICI</a> 

Pour ce faire, nous nous basant sur le calcul des similarités entre les réponses des candidats et les définitions exactes trouvées sur Wikipédia. Deux méthodes de calcul de similarité sont à utiliser, à savoir, la similarité syntaxique et la similarité sémantique.

**Recuperer le dataset
**Réaliser les différentes tâches de prétraitement.

In [25]:
import glob
files=glob.glob('/home/etd/Desktop/M12/TM/TM/corpus-20090418/*')
f_pointers=[open(file,"r",encoding="utf8",errors='ignore') for file in sorted(files)]
corpus=[f.read() for f in f_pointers]
#print(corpus)


In [27]:
nlp = spacy.load('en_core_web_sm')
doc = [nlp(doc) for doc in corpus]

In [13]:
from spacy.lang.en.stop_words import STOP_WORDS
def preprocess(doc_nlp):
    d=[]
    for token in doc_nlp:
        if(not token.text in STOP_WORDS and  token.text.isalpha()):
            d.append(token.lemma_)
    return d

In [14]:
preprocess(doc[0])

['inheritance',
 'basic',
 'concept',
 'Object',
 'orient',
 'programming',
 'basic',
 'idea',
 'create',
 'new',
 'class',
 'add',
 'extra',
 'detail',
 'exist',
 'class',
 'this',
 'allow',
 'new',
 'class',
 'reuse',
 'method',
 'variable',
 'exist',
 'class',
 'new',
 'method',
 'class',
 'add',
 'specialise',
 'new',
 'class',
 'inheritance',
 'model',
 'kind',
 'relationship',
 'entity',
 'object',
 'example',
 'postgraduate',
 'undergraduate',
 'kind',
 'student',
 'this',
 'kind',
 'relationship',
 'visualise',
 'tree',
 'structure',
 'student',
 'general',
 'root',
 'node',
 'postgraduate',
 'undergraduate',
 'specialised',
 'extension',
 'student',
 'node',
 'child',
 'node',
 'in',
 'relationship',
 'student',
 'know',
 'superclass',
 'parent',
 'class',
 'postgraduate',
 'know',
 'subclass',
 'child',
 'class',
 'postgraduate',
 'class',
 'extend',
 'student',
 'class',
 'inheritance',
 'occur',
 'layer',
 'visualise',
 'display',
 'large',
 'tree',
 'structure',
 'for',
 '

On aura besoin que de la lemmatization aprés avoir rendu le doc sous forme de token pour pouvoir faire la similarité syntaxique

## 5.1 similarité syntaxique 

In [38]:
from sklearn.metrics.pairwise import cosine_distances,euclidean_distances
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
tfidf_matrix.shape

#compute similarity for first sentence with rest of the sentences
euclidean_distances(tfidf_matrix[0],tfidf_matrix)

array([[0.        , 1.05990529, 1.33904078, 0.        ]])

**Realiser la même chose en se basant sur les representations OHV et BOW?
**Comparer les performances des trois methodes en terme de temps d'execution et precision.  

## OHV

In [43]:
##
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
freq   = CountVectorizer()
c=[sent.lower() for sent in corpus]
cor = freq.fit_transform(corpus)

#compute similarity for first sentence with rest of the sentences
euclidean_distances(cor[0],cor)

array([[0.        , 2.23606798, 2.64575131, 0.        ]])

## BOW

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['This is the first document.','This is the second second document.','And the third one.','Is this the first document?']
corpus=[ sent.lower() for sent in corpus]
X = vectorizer.fit_transform(corpus)
euclidean_distances(X[0],X)

array([[0.        , 2.23606798, 2.64575131, 0.        ]])

à mon avis le plus précis est le tfidf car il prend en considération meme la fréquence du terme dans
tous le corpus c'est ce qui fait de lui plus précis

Il existe d'autre methodes(orientées caractères) pour le calcule de la similarité syntaxique entre des documents courts (des phrases):

* Longest Common Sequence (LCS)
* Set features
* Word Order Similarity
* n-gram sentences 
* Jaro-Winkler
* ...

Cliquer <a href="http://www.iaeme.com/MasterAdmin/Journal_uploads/IJCET/VOLUME_9_ISSUE_5/IJCET_09_05_001.pdf" target="_blank">ICI</a> pour plus de details



## en utilisant la distance euclidienne on a:

**Calculer les similarités syntaxiques entre les réponses des étudiants et les définitions trouvées sur wikipedia.


In [86]:
from sklearn.metrics.pairwise import cosine_distances,euclidean_distances
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import Binarizer
import time

    
def tfidf_simil(corpus,index_of_doc):
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)
    #tfidf_matrix = tfidf_matrix.toarray()
    #compute similarity for first sentence with rest of the sentences
    return (euclidean_distances(tfidf_matrix[index_of_doc],tfidf_matrix))

def ohv_simil(corpus,index_of_doc):
    vectorizer  = CountVectorizer()
    corpus=[ sent.lower() for sent in corpus]
    corpus = vectorizer.fit_transform(corpus)

    onehot = Binarizer()
    ohv = onehot.fit_transform(corpus.toarray())

    return (euclidean_distances(ohv[index_of_doc],ohv))

def bow_simil(corpus,index_of_doc):
    vectorizer = CountVectorizer(lowercase=True)
    corpus=[ sent.lower() for sent in corpus]
    X = vectorizer.fit_transform(corpus) #sparsy format
    bow = X.toarray()
    
    return (euclidean_distances(bow[index_of_doc],bow))

In [82]:
task1=corpus[::5]
task2=corpus[2::5]
task3=corpus[3::5]
task4=corpus[4::5]
task5=corpus[5::5]

In [85]:
task1[-1]

'In object-oriented programming, inheritance is a way to form new classes (instances of which are called objects) using classes that have already been defined. The inheritance concept was invented in 1967 for Simula.\n\nThe new classes, known as derived classes, take over (or inherit) attributes and behavior of the pre-existing classes, which are referred to as base classes (or ancestor classes). It is intended to help reuse existing code with little or no modification.\n\nInheritance provides the support for representation by categorization in computer languages. Categorization is a powerful mechanism number of information processing, crucial to human learning by means of generalization (what is known about specific entities is applied to a wider group given a belongs relation can be established) and cognitive economy (less information needs to be stored about each specific entity, only its particularities).\n\nInheritance is also sometimes called generalization, because the is-a rela

In [88]:
print("similarité task A")
print(tfidf_simil(task1,-1))
print("similarité task B")
print(tfidf_simil(task2,-1))
print("simil
 25,
 26,
 27,
 28,
 29,
 30,arité task C")
print(tfidf_simil(task3,-1))
print("similarité task D")
print(tfidf_simil(task4,-1))
print("similarité task E")
print(tfidf_simil(task5,-1))

similarité task A
[[1.21604975 1.24146323 0.98659847 0.57204362 0.26714618 1.10777576
  1.19542583 0.8764334  1.23305301 1.20174758 0.81033754 0.56792284
  1.08550258 1.17308256 0.68003071 1.19385364 0.19780116 0.85570628
  1.1399773  0.        ]]
similarité task B
[[0.4776493  0.35426795 1.05784689 0.67935839 1.08044227 0.86041962
  0.68598582 1.01218865 0.39738727 0.93386414 0.89639488 1.24359115
  0.5570358  0.87790326 1.18682773 0.75142571 1.16811934 1.06843693
  0.87737995 0.        ]]
similarité task C
[[0.99924565 0.75573344 0.53520624 1.28972854 1.29019698 0.8226406
  0.87719586 1.13034252 0.94724998 0.49532997 0.84346984 1.01950504
  0.10291656 1.03004416 0.87150202 0.62752808 0.23014385 1.00695851
  1.16894471 0.        ]]
similarité task D
[[1.12133015 0.77006205 0.88812801 1.24260994 0.95933764 1.10916744
  0.8709961  0.95297741 1.00815952 0.60024941 0.92884517 1.03389619
  1.05837247 0.79857418 0.99741824 0.4744536  0.68620107 0.75993597
  1.09606108 0.        ]]
similarit

## 5.2 similarité semantique : Approche lexicale

In [89]:
from nltk.corpus import wordnet as wn 
computer_synsets = wn.synsets("computer") 
print("Computer sens in wordNet:")
i=0;
for sense in computer_synsets: 
    print(" \t Sens :", i)
    print(" \t\t Sens definition: "+sense.definition())
    lemmas = [l.name() for l in sense.lemmas()]
    print("\t\t Lemmas for sense :" +str(lemmas))
    i=i+1

Computer sens in wordNet:
 	 Sens : 0
 		 Sens definition: a machine for performing calculations automatically
		 Lemmas for sense :['computer', 'computing_machine', 'computing_device', 'data_processor', 'electronic_computer', 'information_processing_system']
 	 Sens : 1
 		 Sens definition: an expert at calculation (or at operating calculating machines)
		 Lemmas for sense :['calculator', 'reckoner', 'figurer', 'estimator', 'computer']


In [49]:
from nltk.corpus import wordnet as wn 
import pandas as pd
import numpy as np
computer_synsets = wn.synsets("computer") 
device_synsets = wn.synsets("study") 
lch=[]
wup=[]
print(device_synsets)

for s1 in computer_synsets:
    for s2 in device_synsets:
        lch.append(s1.path_similarity(s2))
        wup.append(s1.wup_similarity(s2))

pd.DataFrame([lch,wup],["lch","wup"])


[Synset('survey.n.01'), Synset('study.n.02'), Synset('report.n.01'), Synset('study.n.04'), Synset('study.n.05'), Synset('discipline.n.01'), Synset('sketch.n.01'), Synset('cogitation.n.02'), Synset('study.n.09'), Synset('study.n.10'), Synset('analyze.v.01'), Synset('study.v.02'), Synset('study.v.03'), Synset('learn.v.04'), Synset('study.v.05'), Synset('study.v.06')]


0         1         2         3         4         5         6   \
lch  0.055556  0.062500  0.066667  0.058824  0.111111  0.066667  0.111111   
wup  0.105263  0.117647  0.125000  0.111111  0.555556  0.125000  0.555556   

           7         8         9   ...        22        23        24  \
lch  0.055556  0.083333  0.066667  ...  0.090909  0.066667  0.166667   
wup  0.105263  0.421053  0.125000  ...  0.444444  0.125000  0.631579   

           25    26    27    28    29    30    31  
lch  0.083333  None  None  None  None  None  None  
wup  0.153846  None  None  None  None  None  None  

[2 rows x 32 columns]

In [50]:
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
def WSD(word, doc):
    context= word_tokenize(doc)
    sens=lesk(context, word)
    return sens

doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'


print(WSD("Computer", doc1).definition())
print(WSD("Computer", doc2).definition())

a machine for performing calculations automatically
a machine for performing calculations automatically


In [51]:
a=WSD("Computer", doc1)
b=WSD("science", doc2)


In [55]:
def semanticD(doc1,doc2):
    nlp = spacy.load('en_core_web_sm')
    doc1_p = nlp(doc1)
    doc2_p = nlp(doc2)
    doc1_p=preprocess(doc1_p)
    doc2_p=preprocess(doc2_p)
    score=0
    print(doc1_p)
    print(doc2_p)
    for tock1 in doc1_p:
        for tock2 in doc2_p:
            syn1 = WSD(tock1,doc1)
            syn2 = WSD(tock2,doc2)
            if syn1 is not None and syn2 is not None :
                x=syn1.path_similarity(syn2)
                if x is not None and x>0.25:
                    sim.append(x)
        if len(sim)!=0:
            score+=max(sim)
    return score/min(len(doc1_p),len(doc2_p))
            
                




In [56]:
doc1='Computer science is the study of computers and computing concepts. It includes both hardware and software, as well as networking and the Internet'
doc2='Computer science is the science that deals with the theory and methods of processing information in digital computers, the design of computer hardware and software, and the applications of computers.'
#def SemanticDistanceDocs(doc1,doc2):
doc1='I m not a pilot'
doc2='I drive airplanes'

#print(SemanticDistanceDocs(doc1,doc2))
print(semanticD(doc1,doc2))

['I', 'm', 'pilot']
['I', 'drive', 'airplane']
1.0


In [57]:
syn1 = WSD('pilote',doc1)
syn2 = WSD('pilote',doc2)
print(WSD("Computer", doc1).definition())
print(WSD("Computer", doc2).definition())

a machine for performing calculations automatically
a machine for performing calculations automatically


In [58]:
x=a.path_similarity(b)
x

0.07142857142857142

**Defnir la fonction SemanticDistanceDocs(doc1,doc2) qui permet de calculer la distance semantique totale entre deux documents texte